; DBÇÃíËã`
HOSTNAME=192.168.x.x
DBNAME=workspace
DBloginID=<your_login_id>
DBpassword=<your_password>
DBNAMENotInQuery=1

;SQLServerîFèÿ
DBAuthentication=-U %DBloginID% -P %DBpassword%
DBAuthenticationforBCP=-U %DBloginID% -P %DBpassword%
;WindowsîFèÿ
;DBAuthentication=-C
;DBAuthenticationforBCP=-T
